# Numpy

In [1]:
import numpy as np

In [2]:
arr=np.linspace(1,3)

In [3]:
my_list=[1,2,3,4,5,6]
var=np.array(my_list)
var

array([1, 2, 3, 4, 5, 6])

In [12]:
my_list=[1,2,3,4,5,6]
var=np.array(my_list)
print(var)

[1 2 3 4 5 6]


In [17]:
list_1=[[1,2,3,4],[1,2,3,4]]
var=np.array(list_1)
print(var)

[[1 2 3 4]
 [1 2 3 4]]


In [4]:
var

array([1, 2, 3, 4, 5, 6])

In [3]:
np.zeros(4)

array([0., 0., 0., 0.])

In [8]:
np.zeros ((2,3))   #2 is rows & 3 is columns    #[] represants dimmensions of array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((3,4)) # 3 is rows and 4 is columns

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.arange(1,5)

array([1, 2, 3, 4])

In [19]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [21]:
np.linspace(0,5)  #it a function gives equal space points

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [22]:
np.linspace(1,3,10)  #1 is start point & 3 is end point & 10 is no.of equal points  

array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
       2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ])

In [23]:
np.eye(1,3)  # identy matrix of 1 row and 3 columns   

array([[1., 0., 0.]])

In [24]:
np.eye(3,3)  #identity matrix of 3x3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.random.rand(2)  # it is method returns random values

array([0.46352278, 0.14026242])

In [26]:
np.random.rand(2,3)

array([[0.537795  , 0.73675892, 0.51799966],
       [0.93647161, 0.87119156, 0.00597172]])

In [27]:
np.random.randn(2)

array([-0.15921127, -0.42505891])

In [30]:
var=np.random.randint(1,50,20)
var

array([28, 38, 30, 19, 44, 10, 44, 24,  9, 40, 18, 35, 16, 11, 31,  2, 20,
       23, 45, 12])

In [35]:
var_2=var.reshape(5,4)
var_2    # we can change shape of the array using reshape fun

array([[28, 38, 30, 19],
       [44, 10, 44, 24],
       [ 9, 40, 18, 35],
       [16, 11, 31,  2],
       [20, 23, 45, 12]])

In [33]:
var.shape # shape of the var array is 1-d with 20 elements

(20,)

In [36]:
var_2.shape  # shape of the array var_2

(5, 4)

In [37]:
var_2.max()   # return max value

45

In [38]:
var_2.min()   # return min val

2

In [39]:
var.argmax()   # return position of the max value

18

In [40]:
var.argmin()     #return position of the min value

15

# indexing and slicing 
  we are seeing cloning

In [42]:
list1=[1,2,3,4,5,6,7,8,9]
arr=np.array(list1)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
slic_of_array=arr[:4]  #created slice of the array 
slic_of_array

array([1, 2, 3, 4])

In [47]:
slic_of_array[:]=99   #changed values of the slice
slic_of_array

array([99, 99, 99, 99])

In [48]:
arr   # we found the main array also changed 

array([99, 99, 99, 99,  5,  6,  7,  8,  9])

In [49]:
copy_array=arr.copy() #we copied array 


In [50]:
slice_of_copy=copy_array[:4]  # we created slice of copied array 
slice_of_copy

array([99, 99, 99, 99])

In [51]:
slice_of_copy[:]=100 # changed values of the slice  
slice_of_copy

array([100, 100, 100, 100])

In [52]:
copy_array  #copied array changed 

array([100, 100, 100, 100,   5,   6,   7,   8,   9])

In [53]:
arr   #but main array is same

array([99, 99, 99, 99,  5,  6,  7,  8,  9])

#  view method

In [17]:
v=np.arange(10)
u=v.view()
u

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
u.shape=2,5
u

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [21]:
v   #printing v

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
u[1,2]=100
v    #  printing v

array([  0,   1,   2,   3,   4,   5,   6, 100,   8,   9])

we observed that by using view method we can change the dimenssions of copied array.if u change the elements copied array then base array also changes

In [24]:
u.flags.owndata   # u  don't have owndata because it is copied from v

False

In [26]:
u.base is v   # v  is base of u,means u is copied from v

True

# indexing and selection

In [5]:
arr_2d=[[1,2,3],[4,5,6],[7,8,9]]
arr_2d=np.array(arr_2d)
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
arr_2d[1][2]   # one way of indexing 

6

In [7]:
arr_2d[1,2]   # another way of indexing 

6

In [10]:
arr_2d[:2,:2]   # indexing in rows and column

array([[1, 2],
       [4, 5]])

In [12]:
arr_2d[:3,:2]   #indexing

array([[1, 2],
       [4, 5],
       [7, 8]])

# conditional indexing

In [14]:
arr=np.arange(1,9,2)    
arr

array([1, 3, 5, 7])

In [16]:
boolen_arr=arr>2  #creats an boolean array 
boolen_arr

array([False,  True,  True,  True])

In [17]:
arr[boolen_arr]    #returns a array of true values

array([3, 5, 7])

In [19]:
arr[arr>2]    # shortcut of above process

array([3, 5, 7])

In [20]:
arr[arr<4]

array([1, 3])

In [25]:
arr2=np.arange(25).reshape(5,5)   #practice
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
arr2[:3,1:5]

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14]])

# array operations

In [35]:
arr3=np.arange(10)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr3 +1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
arr3 -1

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [31]:
arr3 *2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [34]:
arr3 * arr3

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [38]:
arr3 /arr3     # it throws an warning than error    ## 0/0 it nan

C:\Users\Bala Yaswanta Sai\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [39]:
1/arr3    # 1 /0 is infinity

C:\Users\Bala Yaswanta Sai\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

# 3-D Array

In [2]:
a=np.arange(10,40).reshape(5,2,3)   
a

array([[[10, 11, 12],
        [13, 14, 15]],

       [[16, 17, 18],
        [19, 20, 21]],

       [[22, 23, 24],
        [25, 26, 27]],

       [[28, 29, 30],
        [31, 32, 33]],

       [[34, 35, 36],
        [37, 38, 39]]])

In [4]:
a[0][1][2],a[1][0][0],a[1][0][1]   # indexing of three dimenional array

(15, 16, 17)

In [7]:
a[:,:,1]    # extracting of elements in the index 1 in all floors   

array([[11, 14],
       [17, 20],
       [23, 26],
       [29, 32],
       [35, 38]])

In [16]:
a[...,1],a[...,0]  # another way of extracting  elements in the index 1 in all floors  ## using dots

(array([[11, 14],
        [17, 20],
        [23, 26],
        [29, 32],
        [35, 38]]), array([[10, 13],
        [16, 19],
        [22, 25],
        [28, 31],
        [34, 37]]))